---
- name: Install public key
  hosts: workers
  remote_user:  "{{ gcloud_remote_user | default('root')}}"

  tasks:

  - name: Set authorized key took from file
    authorized_key:
      user: "{{ gcloud_remote_user }}"
      state: present
      key: "{{ lookup('file', 'keys/jumpoff.pub') }}"

